version: 2
orbs:
  node: circleci/node@5.1.0
jobs:
  release:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - node/install:
          node-version: '18.8.0'
      - run: node --version
      - run: npm --version
      # - run:
      #     name: Setup Environment Variables
      #     command: |
      #       echo 'export AWS_REST_API_ID="$AWS_DEV_REST_API_ID"' >> $BASH_ENV
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apt-get update
      #       apt-get install -y jq zip python3-pip
      #       ...
      # - run:
      #     name: Deploy functions
      #     command: |
      #       cd functions
      #       ../.circleci/deploy.sh echo
workflows:
  version: 2
  full:
    jobs:
      - release:
          filters:
            branches:
              only: master